services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,apigateway,lambda,iam,cloudwatch,logs
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=0
    ports:
      - "4566:4566"
    volumes:
      - "./.localstack:/var/lib/localstack"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8080:80"
